MINDMEISTER_API_KEY = "28cab625eee15bf5be7a165fc5ebeda8584f5b18f2facd8bd74073e9faf4a8ffe1dd5a5458422300ba0021f7a6044d33a72ca296dcc6906fe906e74b28d0e93f"

GEMINI_API_KEY = "AIzaSyDAgcIPM2-1In-D9U5eSmhUFZKHyToless"

MINDMEISTER_CLIENT_ID = "krSPq-COVmFKiHLaTa9TgCSVkQA2yJPdPkKDQt6QRh0"

MINDMEISTER_CLIENT_SECRET = "mzsBsjuOGFmJ2YNnlMgYU2_HwSB-y4k-tfQKoi1cmUk"

VADOO_API_KEY = "gNI283TWhoS940qEFSvbY31AFT4VUTjIMmY1EVkOKto" 